### ISSUE TITLE
Replace weapon with left trigger

### ISSUE THREAD

**Issue by Chronomize23** [RedBigz/TABGVR#11]
This mod looks really cool and I'm impressed with how good it is already. A suggestion/issue I have/found is that you can't pick up new weapons once your slots are full. IDK what the code is like or anything, but I feel like making so you can hold left trigger to replace your weapon with a highlighted one would be a good addition, similar to how you can do the same in flatscreen by holding E.

**Comment by RedBigz** [comment]
I'll fix this tomorrow — the reason it happens is because I just force a pickup on left trigger since the existing code is a bit messy, and I didn't account for slots. I'll try to implement the same thing flatscreen does.

**Comment by RedBigz** [comment]
The issue should be here: https://github.com/RedBigz/TABGVR/blob/787f8291cf283c5e9569a286dbfbce75703aa341/TABGVR/Player/VRControls.cs#L190-L199
I'll close this issue when it's fixed. Thank you!
